# Generated by Django 5.2.1 on 2025-06-08 11:39

import Auth.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0003_service_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='service',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='customer_pictures/', validators=[Auth.models.validate_file_size], verbose_name='profile picture'),
        ),
        migrations.AlterField(
            model_name='providerprofile',
            name='documents',
            field=models.FileField(blank=True, null=True, upload_to='provider_documents/', validators=[Auth.models.validate_file_size], verbose_name='documents'),
        ),
        migrations.AlterField(
            model_name='providerprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='provider_pictures/', validators=[Auth.models.validate_file_size], verbose_name='profile picture'),
        ),
    ]
